name: Comment with image
description: A GitHub Action to comment a Pull Request with images
author: Maksudul Haque / Olivier Dalang

branding:
  icon: 'image'
  color: 'blue'

inputs:
  upload_to:
    description: 'Service to use for uploading the images. (Options: github_branch, imgur)'
    required: false
    default: 'github_branch'

  images:
    description: 'Comma separated lists of artifacts to upload (supports glob patterns: `tests_artifacts/**/*.gif, tests_artifacts/**/*.png`)'
    required: true

  github_token:
    description: 'GITHUB_TOKEN or Personal Access Token (PAT)'
    required: false
    default: ${{ github.token }}

runs:
  using: 'docker'
  image: 'Dockerfile'
